name: Python tests and build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.9
            env:
              TOXENV: py
          - python-version: "3.10"
            env:
              TOXENV: py
          - python-version: "3.11"
            env:
              TOXENV: py
          - python-version: "3.11"
            env:
              TOXENV: asyncio
          - python-version: pypy3.9
            env:
              TOXENV: pypy3

          # pinned deps
          - python-version: 3.8.17
            env:
              TOXENV: pinned
          - python-version: 3.8.17
            env:
              TOXENV: asyncio-pinned
          - python-version: pypy3.8
            env:
              TOXENV: pypy3-pinned
          - python-version: 3.8.17
            env:
              TOXENV: extra-deps-pinned
          - python-version: 3.8.17
            env:
              TOXENV: botocore-pinned

          - python-version: "3.11"
            env:
              TOXENV: extra-deps
          - python-version: "3.11"
            env:
              TOXENV: botocore

          - python-version: "3.12.0-beta.4"
            env:
              TOXENV: py
          - python-version: "3.12.0-beta.4"
            env:
              TOXENV: asyncio
          - python-version: "3.12.0-beta.4"
            env:
              TOXENV: extra-deps
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        if: matrix.python-version == 'pypy3.9' || contains(matrix.env.TOXENV, 'pinned')  || contains(matrix.python-version, '3.12.0')
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-dev libxslt-dev
      - name: Test with tox
        run: |
          pip install -U tox
          tox
